### ISSUE TITLE
static IP on slicekit GP XL216

### ISSUE THREAD

**Issue by SasaRi** [xmos/lib_xtcp#27]
Hi,

somehow I can't set static IP in the application. I have tried the same code with the latest released version 4.0.2 and app works fine.

I don't know what else should I change so that app uses static IP ? 
Application passes to to uip.c file static IP address set in the main file. 
Since there's no dhcp server on the network, it always gets the local IP 169/254.

Thank you 

Sascha

**Comment by pthedinger** [comment]
There is a bug in UIP that prevents assigning static IP addresses. There is a pull request that has fixed this: 

https://github.com/xmos/lib_xtcp/pull/28/commits/9056101db2657654259c5143463fb7fd571cb813
